name: New server request
description: Request a new server not currently available
title: "[New server]: "
labels:
    - new-server-request

body:
    - type: input
      attributes:
          label: Server name
          description: Which server would you like to request to be added?
      validations:
          required: true

    - type: input
      attributes:
          label: Server homepage
          description: e.g., a GitHub page
      validations:
          required: true

    - type: input
      attributes:
          label: Languages
          description: Which languages does this server target?
          placeholder: typescript, javascript
      validations:
          required: true

    - type: checkboxes
      attributes:
          label: Is this server added in lspconfig?
          description: Is there a server configuration for this server in [lspconfig](https://github.com/neovim/nvim-lspconfig)?
          options:
              - label: "Yes"
              - label: "No"

    - type: textarea
      attributes:
          label: How is this server distributed?
          description: Is the server distributed through a standardized channel (such as GitHub release files, npm, pip, etc.)? Leave empty if you don't know.
