name: Automerge

on:
    check_suite:
        types:
            - completed

jobs:
    run-autogen-script:
        runs-on: ubuntu-latest
        steps:
            - name: Enable Pull Request Automerge
              if: ${{ github.event.issue.pull_request }}
              uses: juliangruber/merge-pull-request-action@v1
              with:
                  token: ${{ secrets.PAT }}
                  pull-request-number: ${{ github.event.issue.number }}
                  merge-method: squash
