name: Automatically assign issues to Issue Triaging project

on:
    issues:
        types: [opened]

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    assign-issue:
        runs-on: ubuntu-latest
        name: Assign to Issue Triaging prjoect
        steps:
            - name: Assign new issues to triaging project
              uses: srggrs/assign-one-project-github-action@1.2.1
              if: github.event.action == 'opened'
              with:
                  project: "https://github.com/williamboman/nvim-lsp-installer/projects/1"
                  column_name: "Needs triage"

            - name: Create a PR comment
              uses: peter-evans/create-or-update-comment@v1
              if: contains(github.event.issue.labels.*.name, 'new-server-request')
              with:
                issue-number: ${{ github.event.issue.number }}
                body: |
                    Hello! Cool! Pull requests are always very welcomed to add new servers. If the distribution of the
                    server is simple, the installation will most likely be so as well (existing server installers may be
                    used for reference!). Otherwise, @williamboman will get around to looking into this ASAP!
