name: Format Checker

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    fmt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup FMT
              uses: JohnnyMorganz/stylua-action@1.0.0
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                # CLI arguments
                args: --check ./lua/
