name: Metadata diff checker

on:
    push:
        branches:
            - 'main'
    pull_request:

jobs:
    setup-project:
        uses: williamboman/nvim-lsp-installer/.github/workflows/setup-project.yml@main
    metadata-diff-check:
        needs: setup-project
        steps:
            - name: Run autogen_metadata.sh script
              run: ./scripts/autogen_metadata.sh
            - name: Ensure there are no diffs
              run: |
                git update-index --refresh
                git diff-index --quiet HEAD --
