name: Run autogen script

on:
    workflow_dispatch:
    schedule:
        - cron: "15 13 * * *"

jobs:
    run-autogen-script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.PAT }}
            - uses: rhysd/action-setup-vim@v1
              with:
                  neovim: true
                  version: v0.7.0

            - name: Clone dependencies
              run: |
                  mkdir -p ~/.local/share/nvim/site/pack/packer/start
                  git clone --depth 1 https://github.com/neovim/nvim-lspconfig ~/.local/share/nvim/site/pack/packer/start/nvim-lspconfig

            - name: Run autogen_metadata.sh script
              run: ./scripts/autogen_metadata.sh

            - name: Commit and push changes
              run: |
                  git config --local user.email "william@redwill.se"
                  git config --local user.name "William Boman (automated)"
                  if git commit -m "run autogen_metadata.lua" -- lua/nvim-lsp-installer/_generated; then
                    git push
                  fi

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v4
              with:
                  add-paths: lua/nvim-lsp-installer/_generated
                  commit-message: run autogen_metadata.lua
                  committer: William Boman (automated) <william@redwill.se>
                  author: William Boman (automated) <william@redwill.se>
                  branch: chore/autogen_metadata
                  branch-suffix: short-commit-hash
                  delete-branch: true
                  labels: automerge
                  title: run autogen_metadata.lua
